### ISSUE TITLE
Feature request: mapbox-js fallback?

### ISSUE THREAD

**Issue by MattSidor** [haoliangyu/angular2-mapboxgl-starter#3]
A fallback to mapbox-js for machines/browsers that do not support WebGL? Ideally lazy loading.

I'm working on this in my own project; I can make a pull request when I figure something out.

**Comment by MattSidor** [comment]
Alternatively, if this falls outside the scope of this project, I'd be happy to just fork it.

**Comment by haoliangyu** [comment]
To be honest, I don't fully understand how serious this problem is, because of my lack of WebGL knowledge. If you are able to make a fork, I will be happy to add a section and a link about your solution in the README file.

**Comment by MattSidor** [comment]
It just became a problem for us today...it turns out that browser support for WebGL !== graphics card support for WebGL, and a large portion of our beta testers weren't able to use our app because they are running machines that are a few years old.

I will let you know if I fork! Thanks so much!
