### ISSUE TITLE
Labels not appearing on map

### ISSUE THREAD

**Issue by skorski** [haoliangyu/angular2-mapboxgl-starter#6]
I just built this from your source and noticed the labels are not appearing on the map for locations.  Any idea why that might have happened?

**Comment by haoliangyu** [comment]
@skorski Is there any error message or screenshot on how your problem may look like?

**Comment by skorski** [comment]
@haoliangyu They actually appear to have returned today.  I'm wondering if something happened with the mapbox style.  I was asking you because I wasn't really sure what the this.baseMaps list was doing in the map service and I wasn't sure if that could have been part of the issue.

Thanks for sharing this project BTW.  It's been incredibly helpful as we are trying to get angular and mapbox to work together.
