### ISSUE TITLE
Adding markers to the map

### ISSUE THREAD

**Issue by ahmadyaqob** [haoliangyu/angular2-mapboxgl-starter#7]
Hey 
Any idea how i can add marker to the map ?
I have this code in app.component.ts but it didn't show any markers on the map the same way for the popup works!
```
     import {LngLat, Map, Popup, Marker} from 'mapbox-gl';

        let marker = new Marker()
        .setLngLat([-96, 37.8])
        .addTo(map);

        this.mapService.marker = marker;
```

**Comment by haoliangyu** [comment]
If you check your DOM tree, you can see a marker has been created. As you use the default element as its content, which is an empty `div`, you are surely unable to see anything.

Unlike Leaflet, Mapbox GL doesn't provide any default marker icon and you need to create yours. Try this and you should see a red square at the [Null Island](https://en.wikipedia.org/wiki/Null_Island).

``` typescript
  let el = document.createElement('div');
  el.style.backgroundColor = 'red';
  el.style.width = '10px';
  el.style.height = '10px';

  let marker = new Marker(el)
      .setLngLat([0, 0])
      .addTo(map);
```

**Comment by ahmadyaqob** [comment]
Thanks man!
